### ISSUE TITLE
Incorrect chord alignment when exporting to PDF

### ISSUE THREAD

**Issue by member238** [quelea-projection/Quelea#110]
I'm running 2019.0 on OSX 10.12.6. I wav previously running 2018.0 on the same system.

I've run into some issues with chords displayed on screen and rendered to print and PDF in 2019.0 that were not issues for me with 2018.0

- Chords in Edit Song mode appear in italics. Perviously they appeared as plain text. Not a negative. Simply noted.
- Chords that were properly aligned in Edit Song mode in 2018.0 have now shifted and need to be realigned.
- Chords projected in Stage View match the alignment of chords in Edit Song mode.
- Chords rendered via Print Song or Export to PDF are significantly misaligned relative to chord positions in Edit Song mode. This was not an issue for me in Quelea 2018.

Thanks for all the hard work. Quelea is far and away the front-runner in the Open-Source Worship Projection software arena. I've tried nearly all of the options and I'm sticking with Quelea. Keep doing what you're doing!

**Comment by berry120** [comment]
Thanks for the kind words! To address each point in turn:

- I believe this was new for 2018.1, so that's to be expected.
- This is again expected (unfortunately). We fixed the stage view chord display in 2019.0 so that it was aligned properly with the chords when using a monospace font (previously the alignment was just based on number of spaces, which was reasonably useless when it came to switching fonts.) Now Quelea will calculate the correct spacing for whatever font you're using on stage view (based on the alignment in the monospaced editor.)
- As above, this was a fix for 2019.0
- This sounds like a bug - I don't think we considered the alignment of exporting chords to PDF when putting the above fix in place. We'll try to get some kind of fix in place for the next release, if feasible to do so.

**Comment by member238** [comment]
Michael,

Good morning! Thanks for the prompt and helpful reply. This all sounds like forward movement to me. The good news from my end is that I’m nearly exclusively casting chords to the URL on mobile devices or using Stage View via an HDMI connection to a projector or stage monitor. So, I’m little hampered by this bug. Still I thought you’d like to know, and apparently you would.

Btw, my day job includes traveling around the world to lead worship for gatherings of mission workers. In that capacity I’ve been using Quelea for many years. I prefer an Open-Source solution to worship projection for several reasons:

I believe in the communal values of Open-Source software. They much more reflective the cultural values of many of my colleagues around the world than do what appear to be the profiteering ambitions of many commercial projects that have become so prevalent in the Christian worship arena.
Many of the folks I serve gather for worship in their local contexts. An Open-Source projection software application is a possibility for them where ones costing hundreds of dollars are simply not.

Quelea provides all worship leaders with an affordable, accessible, professional projection option that is so robust that even some of the top-selling alternatives lack its features. You guys rock!

I know it’s helpful to have Beta testers who are truly putting OS software through the paces and actively reporting bugs and suggesting improvements. If I can be of help to you guys, please let me know.

Finally, how do you guys pronounce Quelea? I’m often asked and never positive.

Grace & Peace

Mark

**Comment by berry120** [comment]
Oh yes, we're definitely always keen to know the bugs that exist, even if we don't have time to fix them right away, so reports are always helpful! ;)

It's always very interesting to here about use cases for Quelea too, so thanks for that. I'd certainly agree with your thoughts on OS software in the church space. I'd have assumed that Christian environments, of all places, would be ones where free and open source software would be most prevalent. For whatever reasons that appears to not be the case, and OS software still seems to be somewhat of a niche. I could talk at length on that topic, but I'll hold myself back! ;)

Pronunciation is an interesting one! It's named after the bird, so pronounced the same as that. I believe the "correct" way is "K-wee-lee-ahh" but we've generally been pronouncing it "K-way-lee-ahh" instead, so I'm not sure we even know!

**Comment by berry120** [comment]
This is now "fixed" in the CI release in that I've switched it to use a monospace font when exporting song PDFs. It's certainly not the prettiest solution, but there's no straightforward way to do the positioning otherwise. I don't think Fop (which is the engine we're using) supports accurate "individual" text positioning like we'd need, so that would mean rewriting that whole component - a lot of work for a feature that's little used in practice.

Something that would be nice (ideal in fact) is if someone developed a Java based PDF export library based on the openlyrics format that dealt with all the positioning of chords, verse numbers, etc. and returned a nice PDF in a user-configurable font. This could be developed completely outside of Quelea, potentially used by other projection packages / utilities as well, and then we could just import & use it as a library. If something like that becomes available then I think we'd definitely use it, but until then it's likely we'll just stick with that monospaced font - unless we get too many complaints! 👍
