### ISSUE TITLE
Limit the maximum number of lines

### ISSUE THREAD

**Issue by jejbr84** [quelea-projection/Quelea#133]
I've got a suggestion for a new feature: limit the maximum number of lines displayed on one sheet.

Currently it is possible to set the maximum number of characters per line and the maximum font size. Quelea will automatically resize the text according to these limits. This is fine if the text is automatically enlarged, but if the text is made smaller then it could become too small to read.

Our current solution is to manually split the sections with a line break, but this has a couple of disadvantages. First, it is a lot of work. Second, the line breaks depend on the maximum number of character setting. If I change this then I need to manually reformat all my songs.

To solve this problem I can come up with two solutions: define a mininum font size, or a maximum number of lines per sheet. I think the latter is the most convenient, because it doesn't depend on the chosen font.

What do you think about such a feature? I made a quick and dirty implementation of this feature, so you can better understand what I'm talking about. I committed this to the fork branch jejbr84/Quelea/autolimit-linecount. The image below shows an example result with the maximum line count set to 5 and the maximum number of characters per line to 33. The source lyrics remain untouched, but the sheets are split up. I think this could be a very cool feature that (as far as I know) other presentation software does not have yet. I probably overlooked some side effects of my changes, but I'm sure we can work that out.

![example](https://user-images.githubusercontent.com/37149907/57199821-0c0c2700-6f84-11e9-9829-1acdd4174685.PNG)

**Comment by berry120** [comment]
This was something we considered in the early days - it's a good idea in theory, but the issue I have with it in practice is that you almost always want to split the sections at an "appropriate" point based on the musical flow of the song, so you're not quickly changing slides half way through a phrase. (Splitting after x number of lines obviously won't give you that.) So eventually I decided that just splitting lines was the more "appropriate" thing to do, and leave splitting the verses up to the operator.

@ArvidNy - I'd be interested to hear your thoughts on this too.

**Comment by ArvidNy** [comment]
I'd have to agree with Michael here; it sounds good in theory but I feel like it might cause an unwanted behavior if it splits in the middle of a sentence. I guess there's no good way to calculate it to always split it at a good point in the lyrics. Personally, I won't want the lyrics to be split into two slides automatically - I want to set it myself to make sure it feels natural to change slides there. 

Of course, if you'd want to split the lyrics at every one or two lines to be able to use the lyrics more or less like subtitles along with a video background (as I've seen more and more churches prefer nowadays) this option could be very helpful instead of having to split the lyrics manually. 

However, for the usage from the screenshot, I think I'd prefer a warning while you are editing a song (or possibly as a warning icon on the item in the schedule to cover for the songs already in the database) that tells you that the current amount of lines will result in a very small font size with the current settings, along with the suggestion to split it into two sections, but let the user do the splitting him-/herself. You would of course not be able to get around the problem with splitting all your songs manually, but you should hopefully only have to do it once.

Perhaps it would also be helpful to be able to preview the slide where the cursor is while you are editing a song. That way you can instantly see when the font size is affected.

**Comment by jejbr84** [comment]
Thank you for giving your thoughts. I understand that you have some doubts about this feature, especially when it was already considered earlier. It also has some impact on the existing code base, because (as I found out) you have to split the slides in an early stage of the process.

However, I still think it might be a good option for some users. You don't have to use it, it's an option, but if (almost) nobody uses the option it would be a waste of effort. I agree with you guys that it is not flawless. You will encounter scentences that might be split at an unwanted place, but I think that it would be okay for the large majority of scentences.

I want to emphasize that my proposal does not split lines (because I agree it would be unwanted most of the times), it moves the complete line to the next slide if it doesn't fit. The first verse in the screenshot has only 4 lines, because the next line wraps to 2 lines and the maximum is set to 5. In (the hopefully rare) case that you don't like the automatic split you can still manually correct it multiple ways. Add a line break to force a scentence to the next slide, concatenate two lines (or use a non-breaking line) to keep them together, or split a line if you want it on the next slide.

Apart from my proposal I also like your warning suggestion. You would have to set a minimum desired font size, because there is no way to know what a 'very small font size' is in general. Like you say it is still manual, but at least you get a warning before you show too smal text to the audience.

**Comment by berry120** [comment]
Closing this one off, as per earlier discussions it's not something we're planning (and no-one else has asked in the interim, so I don't think this feature would be used that often either.)
