### ISSUE TITLE
导入中文歌词出现乱码

### ISSUE THREAD

**Issue by AaronJP** [quelea-projection/Quelea#139]
database-Import-Plain text will display garbled.
导入text歌词入数据库时，歌词标题显示Unkonwn，歌词内容为乱码。

**Comment by DeeTigIT** [comment]
Hello AaronJP,

Some questions for the further analysis of our issue:
- Could you please **attach such a plain text file** to this issue? (resulting in this garble upon import) 
- Are you using the 2019.0 stable version of Quelea? 
- And what flavour of Quelea: Windows/Cross platform/Linux/Mac?

At our church we use UTF-8 (without Byte Order Marker) as the character set for the plain text files.
In total we have converted over 3.000 songs this way, using the plain text import function.

Regards,

Dirk

**Comment by AaronJP** [comment]
[耶稣爱你.txt](https://github.com/quelea-projection/Quelea/files/3194902/default.txt)
hi, Dirk，Thank you for your reply.
yes,I'm using the 2019.0 stable version of Quelea on windows7 64bit.
and I have upload the plain text file.
God bless you .
Aaron

**Comment by ArvidNy** [comment]
Hi Aaron,

I've had a look at the file and it seems to be a matter of file encoding. Your file uses GB18030 which seems to be the Chinese standard, but Quelea can unfortunately only import files using UTF-8, so I'm  afraid you will have to convert the files before importing them to Quelea. If you have a lot of files, I'm sure you can find some tool/script for batch conversion. Just let us know if you need any further assistance. 

Thanks,

Arvid

**Comment by AaronJP** [comment]
Hi Arvid,
Thank you for your solution,It works.
But there is still problem to be solved,The title of the song that I improted shows 'Unkonwn'.
I uploaded the screenshot.
Thanks a lot.
Aaron

![Snipaste_2019-05-20_09-02-20](https://user-images.githubusercontent.com/42953754/57991006-77a2d800-7ade-11e9-9bbf-90edfe9ae90b.png)
![Snipaste_2019-05-20_09-03-25](https://user-images.githubusercontent.com/42953754/57991007-77a2d800-7ade-11e9-8502-ee76e1e52db8.png)

**Comment by ArvidNy** [comment]
If you add a blank line between the lyrics and the title or if you add a title tag it should be picked up automatically. So either like this:

> Song Title Here
> 	(*blank line here*)
> Song lyrics starts here

Or like this:

> Title: Song Title Here
> Lyrics starts here

However, I feel like we probably should resort to the file name if no title is found within the file. Or what do you think @berry120?

**Comment by DeeTigIT** [comment]
Taking the filename as the songtitle has a   disadvantage: some titles have special chars thar are not allowed in the (Windows) file name.

Verzonden vanaf mijn Windows 10-apparaat

________________________________
Van: Arvid Nyström <notifications@github.com>
Verzonden: Monday, May 20, 2019 9:51:27 AM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Comment
Onderwerp: Re: [quelea-projection/Quelea] 导入中文歌词出现乱码 (#139)


If you add a blank line between the lyrics and the title or if you add a title tag it should be picked up automatically. So either like this:

Song Title Here
(blank line here)
Song lyrics starts here

Or like this:

Title: Song Title Here
Lyrics starts here

However, I feel like we probably should resort to the file name if no title is found within the file. Or what do you think @berry120<https://github.com/berry120>?

**Comment by ArvidNy** [comment]
Oh, I didn't mean that we should take the file name instead of anything found within the file, just instead of naming it "Unknown". My guess is that in most cases, if you haven't put the song title anywhere within the file, you have named the file itself in a way that you will know which song it is, even if it does contain all the right characters. If it's still not correct you could always rename it, just like you would have to do either way if it's called "Unknown". Another way of avoiding songs called "Unknown" would of course be to let the user enter a song title directly when importing if no title can be found, though that could be a tad tedious if you want to import a lot of files at the same time.

**Comment by DeeTigIT** [comment]
Arvid,
Thanks for this additional explanation. 🙂
I agree on using filename instead of “Unknown” if nothing else can be found or detected.
Regards and blessings,
Dirk

Verzonden vanaf mijn Windows 10-apparaat

________________________________
Van: Arvid Nyström <notifications@github.com>
Verzonden: Monday, May 20, 2019 11:47:27 AM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Comment
Onderwerp: Re: [quelea-projection/Quelea] 导入中文歌词出现乱码 (#139)


Oh, I didn't mean that we should take the file name instead of anything found within the file, just instead of naming it "Unknown". My guess is that in most cases, if you haven't put the song title anywhere within the file, you have named the file itself in a way that you will know which song it is, even if it does contain all the right characters. If it's still not correct you could always rename it, just like you would have to do either way if it's called "Unknown". Another way of avoiding songs called "Unknown" would of course be to let the user enter a song title directly when importing if no title can be found, though that could be a tad tedious if you want to import a lot of files at the same time.

**Comment by berry120** [comment]
Yup, sounds like a sensible idea to me.

**Comment by berry120** [comment]
Should be fixed in the latest CI release 👍

**Comment by AaronJP** [comment]
我的问题解决了，谢谢各位的详细解答。
My problem has been solved,Thank you for your detailed answers.
@ArvidNy @DeeTigIT @berry120 

Summary:
如果我想导入一个text歌词，需要有以下注意点：
第一、text需要是UTF-8格式的，
第二、歌词内容格式应该是：标题+空行+歌词，或者在标题行加上Title:。如下：
> Song Title Here
> (_blank line here_)
> Song lyrics starts here
 Or like this:
> Title: Song Title Here
> Lyrics starts here

**Comment by berry120** [comment]
Hi Aaron - you've reopened this, is there still an issue?
