### ISSUE TITLE
A vuelto el bug 121 en quelea 2019.1 stable

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#165]
El error de la resolución a vuelto en la versión stable.

**Comment by ArvidNy** [comment]
You're right, we decided to roll back the changes we made to try to resolve the bug #121 when we instead introduced a new bug (#149). Since the scaling bug was not new for Quelea 2019.1, we decided to hold back the change until we have the time to find a proper way to fix #149. We decided the scaling issue was better than it freezing all the time. I'll close this and re-open #121 instead.
