### ISSUE TITLE
Resize preview windows independently of one another

### ISSUE THREAD

**Issue by ImLateImLateForAVery** [quelea-projection/Quelea#193]
Sometimes I can clearly see the live screen, so it would be easier to have more of the live panel taken up by content (verses, choruses, slides, whatever) than by a preview pane, but I can't make it smaller without also shrinking the middle preview pane. 

The search section can be resized independently - I just want that for all the bottom panes!

Thanks

**Comment by berry120** [comment]
Nothing planned to do this so far, but nothing inherently stopping us adding an option for this. @ArvidNy or anyone else, any thoughts?

Side note - this is relatively trivial to do technically, we just create an option for not performing the following bidirectional binding:

https://github.com/quelea-projection/Quelea/blob/a98e719dda0bc631dd9e3a71219d4d33bcbf81e9/Quelea/src/main/java/org/quelea/windows/main/MainPanel.java#L67-L68

If we decide to go ahead, certainly a good first issue / hacktoberfest worthy issue.

**Comment by ArvidNy** [comment]
I don't see any problems with that, so I feel like it could make a good optional feature!

**Comment by berry120** [comment]
Ok, sounds great. Let's not work on this for now in case anyone wants to pick it up for Hacktoberfest. If no-one has by the end of October then one of us can grab it.

**Comment by berry120** [comment]
Clearing milestone for now as this isn't critical, is a good first issue for someone to pick up in future, and we should get 2020.0 out ASAP.

**Comment by PaulD987** [comment]
Seems relatively straight forward to do, only slightly trickier thing than mentioned above is that the divider position is saved when Quelea exits and reloaded on restart. However, I think it is only saving the position of the live divider, so a little bit more work to save both, and reload them independently. Still not too tricky though.

**Comment by PaulD987** [comment]
So, been doing a bit of work on this...

![image](https://user-images.githubusercontent.com/73899671/107428415-7fa87400-6b1a-11eb-83b7-e70a6be202e2.png)

The value on the options will default to true, so that there is no change in behaviour by default when moving up to a version with this feature.

If a user has the dividers unlinked, and then changes the options to set them as linked then the preview panel divider will move to be the same position as the live panel divider, and then they will be linked. This is working on the basis that the live panel is the primary one, so shouldn't move when linking.

If they dividers are linked, and then changed in the options to unlink, then obviously nothing will change on the display (as they would have been in the same position when the options dialog was opened), but they can now be moved independently.

When exiting Quelea, the positions of both dividers are always saved (if linked, they will obviously be the same value).

When starting Quelea, if the dividers are linked then the position for the live panel is used for both live and preview. If not linked, then the divider positions are loaded independently from whatever was previously saved.

 @berry120 @ArvidNy Does that all sound ok and the sort of behaviour you would expect?

**Comment by berry120** [comment]
@PaulD987 That all sounds good to me! If you create a PR that does the above then happy to review.

**Comment by ArvidNy** [comment]
Sounds good to me too!

**Comment by ImLateImLateForAVery** [comment]
I've somehow missed every single update here but got the notification that the issue was closed! THANKS THAT'S GREAT ❤️

**Comment by berry120** [comment]
Thanks! This should have been closed when the original PR was merged back in March, but we missed it somehow 👍
