### ISSUE TITLE
Window Layering Issue on Ubuntu

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#221]
On Ubuntu systems (including derivatives) using the LXDE desktop environment, the output windows for Quelea aren’t layered correctly. From what I have seen, the Video window should be underneath the Projection Window, but that is not the case with LXDE. The Video window is always on top. It seems to put itself on top whenever an item goes live, even when I raise the Projection Window. I have no idea why this happens.

I have seen this happen on two separate machines, one running Ubuntu Studio and the other running Peppermint OS, all of which are based on Ubuntu. I have another machine running Peppermint OS as well, but I had another issue where the Video window was on top of the main screen, with the Presentation Window placed correctly. Sadly, I don't recall how I fixed that problem. 

Quelea is up-to-date with version 2019.1.

Any work arounds for this?

Btw, I also posted this on the [forum](https://quelea.discourse.group/t/output-layering-issues/296/2).

**Comment by berry120** [comment]
Hmm, I'm afraid I haven't managed to reproduce this in Gnome (don't have LXDE to hand to try quickly) - but I suspect it's a case of the `toFront()`, `toBack()` calls in JavaFX probably not working properly on that particular environment.

Unfortunately JavaFX can be a bit flaky in terms of the environments it supports, and since LXDE isn't officially supported, it's possible to run into issues like this.

If you fancy grabbing the cross-platform version and running it with Java 11 to see if that makes a difference, that'd be fab - it may not of course, but if it does then that's another motivation for us to look at migrating at some point.

**Comment by HeyITGuyFixIt** [comment]
On the forum someone said they are experiencing the same issue using the XFCE environment, which is somewhat related to LXDE. I haven't had a chance to try out what you suggested, but I may soon.

**Comment by HeyITGuyFixIt** [comment]
When you say Java 11, you mean JDK 11?

**Comment by HeyITGuyFixIt** [comment]
Assuming you mean JDK 11, I installed that and installed the cross-platform version. I ran it and got this error:
```
Error: Could not find or load main class org.quelea.windows.main.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by HeyITGuyFixIt** [comment]
Had the same issue today while running Quelea 2021.0 on Linux Mint 20 and Cinnamon.

**Comment by berry120** [comment]
We no longer use layering with GStreamer, so this shouldn't still be an issue.
