### ISSUE TITLE
Thumbnails and Actual Font Sizes Inconsistent

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#244]
The Preview and Live thumbnails/previews font size doesn't line up with what is actually being shown. This is in 2020.0 on Linux Mint.
![Quelea 2020 0 Font Size Preview](https://user-images.githubusercontent.com/34974905/76349286-143d9d00-62e0-11ea-9803-5f9533c7d10f.png)

**Comment by PaulD987** [comment]
I think this probably comes down to the same issue as #116. Am investigating at the moment and can recreate.

**Comment by PaulD987** [comment]
I think this specific issue is because the lines are short, and only two of them. This means that we are in the "Maximum font size" case... It appears though that the max font size isn't being scaled depending on the display size. So, on the projection screen on the right it is using the maximum font size as is, and on the left in the preview and live panes it has had to shrink the font a bit to fit it in, but only enough to fit in on the canvas. I think what it should really be doing is scaling the max font size for the preview and live panes based on the ratio of the size of the preview/live panes to the main projector screen. That would then give a more realistic preview.
