### ISSUE TITLE
Quelea breaks with newer updates to Java 8 on some Macs

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#286]
We've had reports of Quelea failing to launch with the latest update to Java 8 on some Macs, failing with the error:

```
*** Terminating app due to uncaught exception ‘NSInternalInconsistencyException’, reason: ‘NSWindow drag regions should only be invalidated on the Main Thread!’
terminating with uncaught exception of type NSException
abort() called
```

See here for more info: https://quelea.discourse.group/t/quelea-failing-to-launch/493

This isn't a problem the Quelea team are able to reproduce, so it's not something we can reliably debug and fix. It could be as simple as adding the `-XstartOnFirstThread` VM argument to the Mac launcher, but we don't want to just do that without being able to recreate the problem, and verify the fix works.

**Comment by ArvidNy** [comment]
This seems to be an issue related to loading the native library for playing videos on Mac: `libAVPlayerJava.jnilib`. @grgarno, if I'm not mistaking you wrote that code. Do you think you'd be able to take a look at it again and see if there's anything we can do about it on our end?

Otherwise I wonder if it might be worth revisiting the vlcj option for Mac again, since that library is supposed to be cross-platform. I remember hearing something about you choosing this path when the VLC support was poor on MacOS, but I was thinking that perhaps that library has matured since then. Or what do you guys think?

**Comment by grgarno** [comment]
Hi Arvid-
I’m not sure I’m at a place where I can look at it, however, maybe with recent chip updates it might be better to go the VLCJ route

Greg Arno

**Comment by berry120** [comment]
@grgarno No worries, thanks for letting us know.

@ArvidNy I think we may need to take a deeper look at the video side of things generally - VLCJ certainly isn't a perfect option either and it's also brought its fair share of issues on windows as well as mac (mainly because of VLC version incompatibilities that are difficult to keep track of.)

If I get time I may investigate video in more detail generally. It may be we can do something clever and more multi-platform with something like GStreamer - it's worth playing around with at least if it could solve these sorts of issues in the future.

**Comment by ArvidNy** [comment]
No problem, @grgarno!

@berry120, sounds good to take a more thorough look at what video library we should use. The less we have to create different solutions for different operating systems in the future, the better. GStreamer does sound like it might be a good option.

Until then, people who use the cross-platform version and encounter this issue could always

1. [downgrade the Java version](https://quelea.discourse.group/t/quelea-failing-to-launch/493/8), 
2. [use the Mac installer instead](https://github.com/quelea-projection/Quelea/releases/download/v2020.0/quelea-2020.0-mac.zip), or 
3. (if I don't misunderstand the code) possibly force VLC to be run instead by adding `use.vlc.javafx.rendering=true` to their `quelea.properties` file.

**Comment by PaulD987** [comment]
Hi, so, new around here, but been using Quelea for a while, on a Mac as well! I believe that the issue is that as part of loading the `libAVPlayerJava.jnilib`, it is interacting with the screen, allocating the initial window etc. This library is loaded in the static of AVPlayerJava, so this appears to not be on the main thread, and hence causing issues. Even back on the 1.8.0_161 Java, where it still works, it is outputting a warning that updating the display not on the main thread is deprecated. My suggestion for how to fix this is to wrapper the load like this: `        Platform.runLater(() -> {
                    System.load(library.getAbsolutePath());
        });`
which will then get it on the main thread for the actual loading (I believe). However, this leads on to MacVideo.java not being very happy doing the `AVPlayerJava.isInit()` call, so needs to wait a bit for it to be loaded correctly! This could be overcome by setting a flag in the runLater in AVPlayerJava to know that the load has actually been done, and then wait in MacVideo for it to actually happen (with a timeout). This does appear to work from my brief testing and can get Quelea up and running on 1.8.0_281 like that. Happy to submit a PR if this seems like a suitable solution... I was thinking something like 10 sec timeout, testing every 50ms or so. Thoughts?
