### ISSUE TITLE
Add suport for bibles the opensong server

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#321]
http://www.opensong.org/home/download
![image](https://user-images.githubusercontent.com/35184132/103478472-f7a1b280-4d94-11eb-9ad5-1583fa4190d8.png)

**Comment by DeeTigIT** [comment]
Possible workaround for RV1960.zip from http://www.opensong.org/home/download:
- Unzip the file : RV1960
- Edit with Notepad++ :
  - convert characterset to : UTF-8 (without BOM)
  - change the first file line:
    from : <?xml version="1.0" encoding="iso-8859-1"?>
    to : <?xml version="1.0" encoding="UTF-8"?>
  - save the file
- Import the file in Quelea

After import edited file in Quelea:

![S1](https://user-images.githubusercontent.com/39883796/103800823-2944a300-504d-11eb-8123-4684034dc29f.JPG)

Original file RV1960 in RV1960.zip:

![S2](https://user-images.githubusercontent.com/39883796/103800929-4da07f80-504d-11eb-991b-026d4a4b3062.JPG)

**Comment by berry120** [comment]
This is due to mismatched encodings - we expect all bibles to be in UTF-8, so if they're not in that format then they'll need converting first.

We may be able to be a bit cleverer about this however - I've created this issue around auto-detecting charsets.

https://github.com/quelea-projection/Quelea/issues/327
