### ISSUE TITLE
Implications of using an online lyrics aggregator as a song database

### ISSUE THREAD

**Issue by kavishdahekar** [quelea-projection/Quelea#326]
_I am a novice when it comes to lyric copyright and licensing so I thought the best way to address my question would be to create an issue here._

Quite often we encounter situations where the worship leader is singing a song that is not currently present in the local db. I church and the worship team are quite small and most have never even heard of CCLI.

Why can't we have quelea try to fetch the lyrics from any online lyrics site (ex: azlyrics.com). Are there any legal implications considering all we are doing is fetching publicly accessible information for using it for private viewing via an open source software? This does amount to "scraping", but does that make it illegal?

**Comment by berry120** [comment]
Afraid this isn't something we'd implement - the long and short of it is that it's a legal grey area, and a maintainability nightmare.

It's a legal grey area because laws change from place to place, and Quelea is designed for the opposite of "private viewing" (instead displaying lyrics to songs & hymns in a public setting.) It's also not how those sites were designed to be accessed, and the website T&C's often forbid it (whether those are enforceable is a different question altogether, but even more complex, and not one I'm really qualified to answer.)

It's also a maintainability nightmare because the code needed to screen scrape is inherently fragile - if azlyrics (or whatever service we're using) change anything in the page layout, then this potentially renders the whole solution useless (with zero warning) until we can come along with an update and fix things.

In theory I agree it'd be great to have, but unfortunately it's just not practical.

**Comment by kavishdahekar** [comment]
Thanks for the clarification @berry120 !
