### ISSUE TITLE
Composing a schedule: handling songs with translation(s)

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#36]
When composing a schedule it is not obvious which songs do have translation(s) and which haven't. Each song has to be inspected individually. In our ceremonies when a song has a translation we always use that one, unless indicated otherwise.

Some thoughts:
- When a song has a translation: always select that one automatically when adding to song to the schedule. (when a song has more than 1 translation select one of those)
- Give some attention "TRANSLATIONS AVAILABLE" or similar (but do not select one automatically).

![vert1](https://user-images.githubusercontent.com/39883796/43882474-0ac925b2-9bb0-11e8-9ca4-adc68382b67a.JPG)
![vert2](https://user-images.githubusercontent.com/39883796/43882483-11f3fef2-9bb0-11e8-8749-94b07d7907c3.JPG)
![vert3](https://user-images.githubusercontent.com/39883796/43882490-14adca2e-9bb0-11e8-9e09-26e6318bc579.JPG)

**Comment by ArvidNy** [comment]
I like the idea to somehow show that there's a translation available. I'm thinking that maybe we could add some kind of icon to indicate it instead?

As for the translation to automatically be selected, I'm not sure that it would be the desired behaviour for all users. Perhaps we should consider adding this as an optional feature in that case, though maybe it might not be needed if we could find an easier/quicker way to select a translation instead.

What I personally would like to see when it comes to handling translations, is an option to easily switch between different translations. Sometimes in our church we want to sing in one language at the time, which usually results in creating a really long song with all the translations (up to four) in the main lyrics, since the only other option is to add a new song for all translations and add all of them to the schedule.

**Comment by DeeTigIT** [comment]
An icon (perhaps: T encircled, like C encircled ©) could help to distingish. For now we'll add the infix 'TRANS' in the titles of these translation equipped songs. For a multi-translation song we would use one long song with translations all on-board as well.

**Comment by berry120** [comment]
There's now a branch with this implemented as an icon: https://github.com/quelea-projection/Quelea/tree/36
![Untitled](https://user-images.githubusercontent.com/7595149/134432164-d8dca5b5-6969-423e-8a02-f902e57b65f3.png)

Interested in any thoughts and whether this is useful or not before merging (@DeeTigIT @ArvidNy )

**Comment by berry120** [comment]
@ArvidNy Very good point, didn't consider that. We'll need to have a play with the colours or background since it wouldn't be very visible otherwise, but I definitely think that's better than using an English letter that might be meaningless to some users.
