### ISSUE TITLE
Song Sequence don't work right, it destroys correct song Order

### ISSUE THREAD

**Issue by DuebelWalter** [quelea-projection/Quelea#367]
When I put a song from Database to Schedule the correct song order get corrupted

In the database the song looks like that
V1 C V2 B
I made a Song Sequence : V1 C V2 C B C

When I put the Song into a Schedule the song is displayed like that:
V1 C C C V2 C C C B C C C 

On the right side is the correct song order, left is the corrupt song order.
I used the Windowsversion from Quelea 2021 (nightly and beta) on a windows 10 Computer.

I made screenshot from this problem
![Screenshot 2021-07-17 214635](https://user-images.githubusercontent.com/86735212/126048121-86092c51-37d6-4e5d-a3c0-597b64ded88c.png)

**Comment by berry120** [comment]
@DuebelWalter Is this a new issue in 2021.0 or do you see it in the current version too?

**Comment by DuebelWalter** [comment]
@berry120 This is a new issue in 2021.0
In 2020.0 song order did not work at all with translations. So in 2021 its getting much better.

**Comment by berry120** [comment]
Hmm, it's not something I've been able to reproduce I'm afraid - does this only happen in set circumstances, like when a song has a translation or something like that? @ArvidNy not sure if you're able to reproduce this.

**Comment by DuebelWalter** [comment]
It only happens when I used a translation on a song, if there was no translation everything was fine.

**Comment by berry120** [comment]
I still don't seem to be able to reproduce it I'm afraid - could you perhaps save it to a schedule file and then upload here?

**Comment by DuebelWalter** [comment]
The Song order bug seems to be fixed Quelea 2021 Beta 2.
 I made my first tests and the song order is always correct even  in a schedule.
 Thank you for the fast fixing of this problem

**Comment by DuebelWalter** [comment]
The problem with the songsequence seems to behave differently now. It always copies the text in the original text to the place where it should be in the verse sequence. But the translation is not changed (as you can see on the first screenshot). The second screenshot shows my song sequence

I have produced the error as follows:
1. create new song
2. create translation
3. save song and copy it into the schedule
4. save sequence
5.close Quelea
6. start Quelea and open the schedule
After that the problem occurred as you can see on the screenshot.
It also occurs when didnt put the song to the schedule
![Song with error](https://user-images.githubusercontent.com/86735212/132554247-1ec8754f-3a50-4325-8fa2-5e3787fcfe0b.png)
![Song sequence example](https://user-images.githubusercontent.com/86735212/132554251-a105ac9a-5d54-4507-b539-6149bf0f116a.png)

**Comment by Youngwily** [comment]
Update - the problem with song sequence corruption appears to happen when copying the song to the schedule, rather than adding it. If added the song is the same as in the database.
If copied then the corruption appears as set out above (no translation involved)
It also seems that songs exported and imported on another computer are also corrupted if they have a sequence.
I think I may have to go through my database and remove all the song sequences, which is a great shame.

**Comment by berry120** [comment]
Should now be fixed in the latest PR - sorry for the delay in this one, was (hopefully) a simple fix after you guys pointed out it was about copying the song to the schedule.

@Youngwily You shouldn't need to remove the song sequences as this was just a display issue rather than anything that should have corrupted the database - hopefully in the CI release it should all now work ok.

**Comment by DuebelWalter** [comment]
In my test of the newest CI-Release the song sequence works perfect, even with translations.
Thank you a lot for fixing this issue, this makes my work on new songs much easier.

**Comment by Youngwily** [comment]
I have also downloaded and tested the latest CI and the song sequence is good when copying the song to the schedule.
