### ISSUE TITLE
Improve the bible search

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#372]
any ideas to improve the bible search engine

![image](https://user-images.githubusercontent.com/35184132/130312040-10e34cfe-d5db-4290-b471-a582b0723e74.png)

**Comment by berry120** [comment]
Afraid you'll need to be much more specific here - how do you want the search improved?

**Comment by Dazmed707** [comment]
that the books can be displayed in a column
when selecting the book, another column with the chapters and another with the verses appears

from there with the cntrl key you can mark up to where you want to add .. and if nothing is marked add the entire chapter

**Comment by berry120** [comment]
I don't think this would make much sense for the bible search dialog - the whole point of that is to search for a word or phrase in a version of the bible and then have the book / chapter / verse provided to you. So we wouldn't be looking to add any kind of input similar to this into that dialog. Bible search and bible browsing is also a bit of a niche feature that isn't used a great deal, so we wouldn't be treating improvements in those areas as a priority.

If we're talking about using this as to define a bible passage to add to a schedule, things get a bit more interesting. This is a UI area that, I think, could do with some improvement - the syntax for defining what to add isn't obvious, there's a disconnect between the books / chapter&verse (books are a dropdown, chapter/verse is freeform text) and in general it looks more than a tad cluttered.

The problem is, UI is *hard*. I can't decide how we should fix it, or even if we *can* fix all those issues without making other significant sacrifices. Feasibly, we could add a dialog similar to above that let you select by book / chapter / verse. The problem with this is I personally think it's significantly *worse* than what we have currently - it takes lots of mouse clicks to add even the simplest 1 verse example, it's a big, overwhelming dialog to look at, and there's no obvious way to support cross-chapter passages (how would you click here to add Genesis 1:31-2:1 as a single section?) We could add it as an option or separate dialog, but I'm very reluctant to do that sort of thing - all we'd achieve there is to tack on a second, sub-optimal way of doing the same thing as we can achieve currently.

All in all I'm open to discussions about the UI elements around this area and very interested to see any mockups if anyone has any ideas as to how we can improve what we have currently, but we'd have to have long discussions and likely multiple revisions before we could consider any changes here.
