### ISSUE TITLE
Quelea songpack multiplies verses & etc. when Song sequence is used

### ISSUE THREAD

**Issue by DuebelWalter** [quelea-projection/Quelea#522]
I exported songs on my PC to Quelea Song Pack and reimported them on our Church PC.
After the Reimport The verses and Chorus, etc. was in the song sequence (as it should be). and also as real Text in the Song Field.
I made picture of a song before and one after the export.
I worked with Quelea 2022 Beta 1

The Song before the export:
![Screenshot 2021-12-08 222141](https://user-images.githubusercontent.com/86735212/145286941-097fb00f-ecd5-4d9a-9968-813df0ecc588.jpg)

The song after the export:
![Screenshot 2021-12-08 222703](https://user-images.githubusercontent.com/86735212/145287063-a1605e12-cc5a-4cbc-a598-849a6b7a7516.jpg)

**Comment by DeeTigIT** [comment]
@berry120, @ArvidNy 
I did some investigation into this with 2 songs: identical in lyrics, one without song sequence, the other with song sequence.

![S1](https://user-images.githubusercontent.com/39883796/148446935-34e8f58b-cedb-43f9-820f-d0c560c1f223.JPG)

Exporting them to a Quelea Songpack (testsong.qsp) and inspecting the contents:

![S2](https://user-images.githubusercontent.com/39883796/148447185-bc678e7e-4b53-4eb0-8d63-87c363f0382e.JPG)

**Note that testsong_seq (right side) is exported as xml to the .qsp using song sequence translation in the same way as during projection of this song. I wonder if that is correct: should not the original song contents, without any song sequence translation, be exported as xml to the .qsp?**

After importing testsong.qsp into an empty Quelea database:

![S4](https://user-images.githubusercontent.com/39883796/148447985-617eca35-b3bf-4128-9dd1-7b5019948c74.JPG)

For testsong_seq we see the issue described by @DuebelWalter

As a test I built a new Songpack (testsong_corr.qsp) with an additional song testsong_seq_corr having:
- xml based on original song contents (without any song sequence translation)
- song sequence attribute: V1 C V2 C V3 C B C V4

![S5](https://user-images.githubusercontent.com/39883796/148448684-ec24f2e9-d179-402b-9e65-eecb9ac0399b.jpg)

And importing testsong_corr.qsp into an empty Quelea database:

![S6](https://user-images.githubusercontent.com/39883796/148448809-e206fa82-bc5a-4628-b98c-bcfca714e53a.JPG)

Note that for song testsong_seq_corr (right side):
- it has the original song contents (during the importing no song sequence translation is applied, apparently)
- in the preview pane we see the correct order V1 C V2 C V3 C B C V4

Song sequencing was introduced in Quelea release 2020.0 Churches,  using song sequencing en making exports using the Quelea Songpack, will encounter problems with their sequencing when they import/restore the Song Pack.
**Can this issue be labelled as a bug**?

[testsong.qsp.zip](https://github.com/quelea-projection/Quelea/files/7824665/testsong.qsp.zip)

[testsong_corr.qsp.zip](https://github.com/quelea-projection/Quelea/files/7824669/testsong_corr.qsp.zip)

**Comment by DeeTigIT** [comment]
See also:
 Quelea Song Pack format seem lossy #301

**Comment by Youngwily** [comment]
This is still an issue in version 2022 beta2

When **importing** a songpack into quelea, the song sequences in the imported songs are corrupted, the preview screen shows multiple instances of choruses or verses, depending on the sequence. 

If a song sequence is added to a song in the database manually, or a new song added, then the song sequence works fine - so it would appear it is the importing action that causes the problem.

As a workaround, instead of **importing** the songpack, add it to quelea by copying and pasting the "c:/users/_username_/.quelea/database_new" folder from the source PC, and song sequences are displayed properly.

This is possibly related to the issue #367 previously fixed

**Comment by berry120** [comment]
An attempted fix has been pushed for this and so it should be in the CI release shortly (https://github.com/quelea-projection/Quelea/releases/tag/CI-RELEASE) - any tests would be much appreciated 👍

**Comment by Youngwily** [comment]
[testsongpack.zip](https://github.com/quelea-projection/Quelea/files/8389493/testsongpack.zip)

HI

I have downloaded and installed the latest CI release, but the import still changes the song sequence when I import songpack file attached.
The file has only one song (10,000 reasons) and it has the sequence C1 V1 C1 V2 C1 V3 C1, but when imported the song is displayed as C1 C1 C1 C1 V1 C1 C1 C1 C1 V2 C1 C1 C1 C1 V3 C1 C1 C1 C1 

hope this helps
Brian

**Comment by Youngwily** [comment]
attached are screenshots of the 'edit song' of the original song before export (originalsong.jpg) and the 'edit song' view of the imported song (importedsong.png) 
I guess it could be the export that is changing the song, rather than the import? 

Is there a way I can open the songpack.qsp file to see the file contents?

The song was exported from 2021 stable release and imported into the latest CI of 2022beta2
![importedsong](https://user-images.githubusercontent.com/89409830/161063228-a6b3e276-7a15-4329-894d-547d4c138f34.png)
![originalsong](https://user-images.githubusercontent.com/89409830/161063233-78f84533-28c6-4b7c-a583-732662d6776c.jpg)

**Comment by berry120** [comment]
> I guess it could be the export that is changing the song, rather than the import? 

It is - unfortunately there's nothing we can do about song packs exported from older versions already, but if you export / import both on 2022.0 CI release then you shouldn't have an issue.

The qsp file is just a zip file, and the songs in it are just XML files, so easy enough to take a look in a text editor if you're curious :-)

**Comment by Youngwily** [comment]
Hi Michael

Thank you so much for your help with this, it really is appreciated. I have tested the export and import in the CI release and it looks to be fixed! Thanks once again.I will do some more testing just to be sure.

However, when I tried manually adding a new song it didn’t appear in the song list until I shutdown Quelea and restarted it.

This works ok in 2021 so is it a new bug? I can log a new call if needed.

Thanks
Brian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Youngwily** [comment]
Hi Michael

I unistalled and reinstalled Quelea (2022beta CI release) and adding a new song manually works fine

thank you
Brian

**Comment by DuebelWalter** [comment]
Hi Michael,
I could export our church song database  as qsp fille to my pc and back and everything works fine. Thank you for fixing this issue.
