### ISSUE TITLE
Export order of service to pdf - only songs listed

### ISSUE THREAD

**Issue by Youngwily** [quelea-projection/Quelea#542]
'Export order of service to pdf' does not include Bible verse, etc but only lists the songs in the Order of Service

**Comment by berry120** [comment]
This could be a task someone can work on for Hacktoberfest. The relevant change isn't Java based, just XSL based, so will need to be made in the `scheduleformat.xsl` file.

At the moment in that file you'll see a for-each block for "song", but not for any other elements, which is why they're not in the resulting PDF.

**Comment by island-coder** [comment]
@berry120  Where can I locate the other elements to be included ?

**Comment by prakhar-198** [comment]
@berry120 please assign me this I'll fix it!

**Comment by berry120** [comment]
@island-coder Sorry, missed your earlier question. The XML tags for other elements can be found in the relevant classes that implement `Displayable`, in the getXml() method. For example, `BiblePassage` uses `passage` as its element name.

**Comment by berry120** [comment]
Fixed with #542
