### ISSUE TITLE
Use Collection.addAll instead of loop

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#570]
ImageGroupDisplayable.getResources() method uses a loop to add a bunch of `File` objects to a new `ArrayList`. Instead of this we could just use `Collections.addAll()`.

**Comment by suhaas-livcd** [comment]
Hi @berry120 , I would like to work on this issue.

**Comment by Ashpreetwadhwa** [comment]
hey @berry120 i would like to do this task

**Comment by berry120** [comment]
@Ashpreetwadhwa Afraid this one is already assigned.

**Comment by suhaas-livcd** [comment]
@berry120 

- I have check the issue, [ImageGroupDisplayable.java](https://github.com/quelea-projection/Quelea/blob/master/Quelea/src/main/java/org/quelea/data/displayable/ImageGroupDisplayable.java#L140)
- I understand, we have to convert use `Collections.addAll(f, files);` instead of iterating over files and adding to list.
- My Doubts : 
  1. As per the [addAll(Collection)](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#addAll-java.util.Collection-) documentation, it returns `boolean` if the list is added. Should I LOG the return value too or just add `Collections.addAll(f, files);` ?
  2. Should I change method comments too ?

**Comment by berry120** [comment]
No need to log the value, and no need for any new comments as the functionality will be identical to the current implementation, just more concise.

**Comment by suhaas-livcd** [comment]
@berry120 Thank you for the information.
I have created the PR #583 but the build check has failed. How should I proceed further ?

**Comment by berry120** [comment]
Thanks!
