### ISSUE TITLE
How do I create an installer package from InteliJ for Windows 11.

### ISSUE THREAD

**Issue by JessyJP** [quelea-projection/Quelea#599]
As the title says, I would like to create an installable .exe or .msi package for Windows 11.
I tried the various .gradle tasks but they didn't produce anything of the sort

**Comment by berry120** [comment]
Sorry, missed this entirely - but since it's not an issue it'd be better suited to https://quelea.discourse.group/.

In short, you'll need to install Innosetup and then run the "dist" Gradle task, which should produce all 3 installers. (Innosetup is Windows only, but does run under wine ok - this is how the CI build works while still using Ubuntu as its base.)

**Comment by JessyJP** [comment]
Wow, that actually works!
