### ISSUE TITLE
Thumbnail size not big enough

### ISSUE THREAD

**Issue by kanglinyao** [quelea-projection/Quelea#61]
I am using 500 as the thumbnail size, but it is still not big enough to show characters on slides. I am suing Chinese in those slides, but some Chinese characters are shown as white boxes. 
Please 
1. let users decide the maximum thumbnail size;
2. improve Chinese support;

**Comment by berry120** [comment]
Thanks for the report - few questions / notes here:

 - What do you mean by the thumbnail size? Are you referring to the size of the image and video preview thumbnails in the library pane, or something else?
 - We haven't extensively tested at all for Chinese character support yet as there hasn't been the demand. We'd certainly appreciate a Chinese translation of the interface, and we could work from there to ensure the characters were displayed properly in the interface.
 - If Chinese characters aren't displaying properly in Video and Image preview, then that's going to be an issue with the image or video rather than Quelea.
 - If Chinese characters aren't displaying properly in Powerpoint slides, that's either an issue with MS Powerpoint / the fonts installed (if you're choosing to use MS Powerpoint directly to show presentations) or the Apache POI library (if you're using it out the box, or you see issues on the slide thumbnails themselves.) If it's with MS Powerpoint then there's nothing we can do about that, as it's closed source / proprietary. If it's the POI library then we'd have to contribute to that directly to fix it, which is theoretically possible (but contributing to third party products is always going to be more of a hassle and take longer than fixing things in Quelea directly, so we couldn't promise any timescales.)

There's likely a few separate issues here, so when we've worked out exactly what needs to be done, I'll separate those out 👍

**Comment by kanglinyao** [comment]
Hi Berry:
Thank you for the quick reply. I'm sorry for not being clear about the issues I reported.
The environment:
Windows 10 Pro and Office Pro 2016 (English Version)
We are also testing Quelea on Mac OS(High Sierra) with Office 2019(English Version)
Quelea: CI 2019
The issues are similar in Mac OS and Windows.
For your questions:
1. The Thumbnail size for the live view is not big enough to show Chinese characters clearly. The person controls the screen projection might need to see the content of those powerpoint slides. It might be caused by a small live view size or the way it is rendered.
2. Chinese churches usually use Chinese simplified and traditional at the same time in PowerPoint slides. The office has very good support for both character sets. Both Chinese character sets show up correctly in presentations.  I hope the office uses UTF-8 for both. I am pretty sure Quelea cannot show those character sets properly.
3.  MS PowerPoint English version or Chinese version deals with Chinese character sets very well. We never have any problem showing Chinese characters.

* I can contribute to the translation of Chinese interface by the way.

**Comment by berry120** [comment]
No problem - thanks for the clarifications. Few further points:

1. Just to check, you mean the thumbnail previews of each powerpoint slide, rather than the preview of what's currently displaying on the screen?
2. If you could send on a Powerpoint file that doesn't display in Quelea properly (even if it's just a single slide with some characters that don't show) that'd be very helpful.
3. This makes sense - I would've been surprised if it was a bug in MS powerpoint over this.

If you could contribute a Chinese translation then that would be amazing!

If you want to do that then you can create a copy of the gb.lang file [here](https://github.com/quelea-projection/Quelea/blob/master/Quelea/languages/gb.lang), and translate all the text on each line on the right hand side of the equals "=" sign to Chinese. The left hand side of the equals sign must be left as is.

Thanks!

**Comment by kanglinyao** [comment]
The projector(second screen) shows the slides normally in term of size, but some Chinese characters are just boxes. The Quelea's main window shows the thumbnail of the live view, but the characters in those thumbnails are too small to see. If I use powerpoint directly, Chinese characters show up correctly and the thumbnails are also clear in lecturer's view.

I will go ahead and create a Chinese translation for Quelea.
[测试中文.pptx](https://github.com/quelea-projection/Quelea/files/2527604/default.pptx)
[test2.pptx](https://github.com/quelea-projection/Quelea/files/2527606/test2.pptx)

**Comment by berry120** [comment]
@kanglinyao I've split off the two separate issues from this one so we can keep track of any future work on them separately. (Can't promise anything around timescales however.) Thanks very much for the report, and feel free to open a PR when you have the Chinese translation!
