### ISSUE TITLE
2024.0 CI - user option 'Copy song to schedule by default' is ignored with 'Add to schedule'

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#630]
The user option 'Copy song to schedule by default', when set, seems to be ignored when a library is added to the schedule with 'Add to schedule' (right-click lib song). This applies for a single selected song as for the the multiple song selection.

When a double click a single song or drag-and drop a single song (multiple selection not yet possible) this option is nog ignored and works as expected.

**Comment by berry120** [comment]
Hmm, I think this might actually be the correct behaviour, but perhaps it isn't worded very well. When right clicking there's two options - both "add" and "copy", and this option was (I think) just meant to switch what happens when you double click. I think it'd be confusing if the option made "add" and "copy" behave the same way.

Perhaps the option's text should be named something like "Copy song to schedule on double-click" instead?

**Comment by DeeTigIT** [comment]
I must have been half asleep when I files this one.
There indeed "add" and "copy" in the right click menu.
The behaviour of "add" and "copy" must be independant (I think) of the setting of the user option.
**I think this issue can therefore be withdrawn.**

The 'Copy song to schedule by default' option is applied upon:
- Double-click a single song
- Drag-and-drop a single song
- Drag-and-drop a multiple song selection

Changing the option text to "Copy song to schedule on double-click" doesn't take "drag-and drop" into account.
**Perhaps it's stays 'Copy song to schedule by default' for now?**

**Comment by berry120** [comment]
That's true - and no worries! I'll close this one off and we'll leave as-is for the moment at least. Can always re-discuss later if anything else comes to light.
