### ISSUE TITLE
Respect image aspect ratio in global theme panel

### ISSUE THREAD

**Issue by dmcharpentier** [quelea-projection/Quelea#93]
Hello,

The Global Theme panel (in 2019.0 b1) is not displaying the correct aspect ratio of images nor is it referencing the aspect ratio of the projecting screen. It seems to be stuck in 4:3 and as a result while the text is rendering fine the images are stretched. I have attached an image of the issue.
![screenshot_5](https://user-images.githubusercontent.com/1699914/51804243-587cf380-222c-11e9-9ef4-7f833dc6743c.png)

Also the Global theme panel is quite squashed vertically (which I'm guessing is a glitch). My suggestion would be to add the ability to grab a corner and expand the box or just make it taller.

Thanks,
Dylan

**Comment by berry120** [comment]
I don't think the global theme panel has ever displayed the correct aspect ratio - it's really just meant as a quick preview rather than an exact representation. We wouldn't update the aspect ratio of the previews, but we could maybe change it so the images don't stretch.

Probably not for this release, but maybe 2019.1.

**Comment by dmcharpentier** [comment]
This works for me! I think my big issue was that the panel was vertically so short and the images stretched vertically and both combined make it hard to scroll through and select one quickly. Hopefully that makes sense!

**Comment by berry120** [comment]
Hmm, taking another look here this behaviour is "correct" in that we don't preserve the aspect ratio of images on the projection screen either. This is deliberate, since otherwise ugly black borders will potentially appear where the text would go (and I don't think we'd go to the time and trouble of detecting the aspect ratio of the image and making sure the words fit nicely within that image - it's a heck of a lot of work for a very niche case.)

However, I think there was still an issue here in that the previews were actually square (1:1) which doesn't seem right. I've changed that now as it seems to make sense (very few screens are square) and while not all images will look great, they should generally look a lot better than they did.

This also has the advantage of reducing the vertical height that each row takes up, making the panel seem less squashed.
